package modules

import (
	"html"
	"math/rand"
	"time"

	tg "github.com/amarnathcjd/gogram/telegram"
)

var icebreakerQuestions = []string{
	"If you could time travel to any era, which would you pick and why?",
	"What is one skill you wish you could learn overnight?",
	"If you could have dinner with any historical figure, who would it be?",
	"What is the most spontaneous thing you have ever done?",
	"If you could live in any fictional world, which one would you choose?",
	"What is the best piece of advice you have ever received?",
	"If you had to eat one meal for the rest of your life, what would it be?",
	"What is your favorite childhood memory?",
	"If you could instantly master any musical instrument, which one would it be?",
	"What is the weirdest food combination you actually enjoy?",
	"If you could be fluent in any language, which one would you choose?",
	"What is something on your bucket list that might surprise people?",
	"If you could swap lives with anyone for a day, who would it be?",
	"What is the strangest dream you can remember?",
	"If you could rename yourself, what name would you pick?",
	"What movie can you watch over and over without ever getting tired of?",
	"If you won the lottery tomorrow, what is the first thing you would buy?",
	"What is one thing you have always wanted to try but have not yet?",
	"If you could only listen to one album for a year, which would it be?",
	"What is your most controversial food opinion?",
	"If you could have any animal as a pet, what would it be?",
	"What was your favorite cartoon growing up?",
	"If you could pick a superpower that is not flight or invisibility, what would it be?",
	"What is a book that completely changed your perspective on something?",
	"If you could live in any city in the world, where would you go?",
	"What is the most useless talent you have?",
	"If you had to teach a class on anything, what would you teach?",
	"What is the best concert or live event you have ever attended?",
	"If you could un-invent one thing, what would it be?",
	"What is your go-to comfort food on a bad day?",
	"If you could meet your future self ten years from now, what would you ask?",
	"What is the most beautiful place you have ever been?",
	"If you could only keep three apps on your phone, which would they be?",
	"What is a fashion trend you never want to see come back?",
	"If you could turn any activity into an Olympic sport, what would you have a chance of winning at?",
	"What is the silliest reason you have ever gotten into an argument?",
	"If you had to delete one social media platform forever, which would it be?",
	"What is the best gift you have ever received?",
	"If you could write a memoir, what would the title be?",
	"What is something you used to love but cannot stand now?",
	"If you could automatically be good at one sport, which would it be?",
	"What is the strangest thing you believed as a child?",
	"If aliens visited Earth, what one thing would you show them?",
	"What is the longest you have gone without sleep, and why?",
	"If you could only wear one color for the rest of your life, what would it be?",
	"What is the most rebellious thing you ever did as a teenager?",
	"If you had a warning label, what would it say?",
	"What is the funniest movie you have ever seen?",
	"If you could give your past self one piece of advice, what would it be?",
	"What hobby would you get into if time and money were no object?",
	"If your life had a theme song, what would it be?",
	"What is one thing you can do that most people cannot?",
	"If you could star in any TV show, which would it be?",
	"What is the worst haircut you have ever had?",
	"If you could relive one day from your life, which would it be?",
	"What is a small thing that always makes you smile?",
	"If you could redesign your bedroom right now, what would it look like?",
	"What is the most spontaneous trip you have ever taken?",
	"If you could erase one memory, would you, and which one?",
	"What is your favorite season and why?",
	"If you could pick the soundtrack to your day, what would the first song be?",
	"What is the best Halloween costume you have ever worn?",
	"If you could open any kind of shop, what would you sell?",
	"What is a phrase you say way too often?",
	"If you had to give up one sense, which would you give up?",
	"What is your most prized possession?",
	"If you were stranded on a deserted island, what three items would you want?",
	"What is the weirdest thing you have ever Googled?",
	"If you could swap places with anyone in this room for a day, who would it be?",
	"What is your favorite smell that reminds you of home?",
	"If you could write a letter to someone, dead or alive, who would it be to?",
	"What is the most embarrassing song on your playlist?",
	"If you could become an expert in one subject, what would it be?",
	"What is the best decision you have ever made?",
	"If you could change one rule in society, what would it be?",
	"What is your favorite way to spend a rainy day?",
	"If you had to pick a different career right now, what would it be?",
	"What is the most useful thing you learned in school?",
	"If you could solve one world problem, which would you tackle?",
	"What is a tradition you would like to start?",
	"If you could be invisible for a day, what would you do?",
	"What is the bravest thing you have ever done?",
	"If you had a personal mascot, what would it be?",
	"What is a smell you absolutely cannot stand?",
	"If you could remove one food from existence, what would it be?",
	"What is a small luxury that makes a big difference in your life?",
	"If you had to perform in a talent show right now, what would you do?",
	"What was your favorite toy as a kid?",
	"If you could spend a year doing anything without consequence, what would it be?",
	"What is the most underrated movie you have ever seen?",
	"If you could combine two animals to make a new one, what would you create?",
	"What is your favorite holiday tradition?",
	"If you could appear in any book, which one would you choose?",
	"What is one thing you have changed your mind about recently?",
	"If you could make one rule that everyone had to follow, what would it be?",
	"What is the kindest thing a stranger has ever done for you?",
	"If you had to give a TED talk tomorrow, what would it be on?",
	"What is one thing you do for fun that you are surprisingly good at?",
	"If you could trade lives with any fictional character, who would it be?",
	"What is the most interesting fact you know?",
	"If you could only drink one beverage besides water for life, what would it be?",
	"What would your dream weekend look like from start to finish?",
}

var wouldYouRatherQuestions = []string{
	"Would you rather be able to fly or be invisible?",
	"Would you rather have unlimited money or unlimited time?",
	"Would you rather always be 10 minutes late or always be 20 minutes early?",
	"Would you rather live without music or without movies?",
	"Would you rather speak every language fluently or play every instrument?",
	"Would you rather lose your sense of taste or your sense of smell?",
	"Would you rather live in space or under the sea?",
	"Would you rather never be able to use the internet again or never watch TV again?",
	"Would you rather have the ability to teleport or read minds?",
	"Would you rather be the smartest person in the room or the funniest?",
	"Would you rather always have to whisper or always have to shout?",
	"Would you rather give up coffee or give up cheese forever?",
	"Would you rather have a rewind button or a pause button for your life?",
	"Would you rather know how you will die or when you will die?",
	"Would you rather have a personal chef or a personal driver?",
	"Would you rather fight one horse-sized duck or one hundred duck-sized horses?",
	"Would you rather live in a treehouse or a houseboat?",
	"Would you rather have free Wi-Fi anywhere or free coffee anywhere?",
	"Would you rather be famous for something silly or unknown for something amazing?",
	"Would you rather have a flying car or a self-cleaning house?",
	"Would you rather always be cold or always be hot?",
	"Would you rather be able to talk to animals or fluently speak any human language?",
	"Would you rather have a photographic memory or be able to forget anything at will?",
	"Would you rather live forever or live a normal lifespan but be remembered forever?",
	"Would you rather have a personal robot or a personal genie with limited wishes?",
	"Would you rather never have to sleep or never have to eat?",
	"Would you rather be able to control fire or water?",
	"Would you rather have super strength or super speed?",
	"Would you rather lose all of your old memories or never be able to make new ones?",
	"Would you rather be stuck in an elevator with someone you do not like or with someone who never stops talking?",
	"Would you rather only be able to listen to one song for the rest of your life or never listen to music again?",
	"Would you rather have free flights for the rest of your life or free food for the rest of your life?",
	"Would you rather be a famous actor or a behind-the-scenes director?",
	"Would you rather know every language ever spoken or be a master at every sport?",
	"Would you rather have hands for feet or feet for hands?",
	"Would you rather be able to breathe underwater or in space?",
	"Would you rather have a rewind button for your life or a pause button?",
	"Would you rather never be able to lie or never be able to tell the truth?",
	"Would you rather be the best player on a losing team or the worst player on a winning team?",
	"Would you rather have the power to heal or the power to teleport?",
	"Would you rather only eat your favorite food for the rest of your life or never eat it again?",
	"Would you rather be ridiculously beautiful or ridiculously rich?",
	"Would you rather always know when someone is lying or always get away with lying?",
	"Would you rather live in a world without seasons or without holidays?",
	"Would you rather be stranded on a beautiful island alone or in a crowded city full of strangers?",
	"Would you rather be a child your whole life or an adult your whole life?",
	"Would you rather have free unlimited streaming services or free unlimited books?",
	"Would you rather live without your phone for a year or live without sweets for a year?",
	"Would you rather be reincarnated as a cat or a dog?",
	"Would you rather have to sing everything you say or dance everywhere you go?",
	"Would you rather have a permanent stutter or a permanent lisp?",
	"Would you rather work your dream job for low pay or a boring job for high pay?",
	"Would you rather be famous but poor or rich but unknown?",
	"Would you rather travel back in time to meet your ancestors or to the future to meet your descendants?",
	"Would you rather have super hearing or super sight?",
	"Would you rather be able to control time or control gravity?",
	"Would you rather find true love or win the lottery?",
	"Would you rather live in a world made of jelly or chocolate?",
	"Would you rather always have to sing instead of speak or dance everywhere you walk?",
	"Would you rather have a third eye or a third arm?",
	"Would you rather give up showers or give up brushing your teeth for a month?",
	"Would you rather have to wear a wedding dress or tuxedo every day for a year?",
	"Would you rather travel the world on a strict budget or stay home with unlimited money?",
	"Would you rather be famous on social media or famous in real life?",
	"Would you rather always speak in rhymes or only in song lyrics?",
	"Would you rather lose all your photos or all your contacts?",
	"Would you rather have free coffee for life or free pizza for life?",
	"Would you rather be the funniest person in the room or the most attractive?",
	"Would you rather be able to change the past or see into the future?",
	"Would you rather be the hero or the villain in a movie?",
	"Would you rather get caught singing in the shower or caught talking to yourself?",
	"Would you rather only watch movies you have already seen or only listen to music you have already heard?",
	"Would you rather have unlimited battery life on your phone or unlimited storage?",
	"Would you rather sweat mayonnaise or have permanent fish breath?",
	"Would you rather be feared by all or loved by all?",
	"Would you rather lose the ability to read or lose the ability to speak?",
	"Would you rather have to wear the same outfit every day or have to change outfits every hour?",
	"Would you rather have an unlimited gift card to Amazon or to a grocery store?",
	"Would you rather have a pet dragon or a pet unicorn?",
	"Would you rather be able to copy any talent you see or always know what is on someone's mind?",
	"Would you rather live in a world without music or a world without art?",
}

func IcebreakerHandler(m *tg.NewMessage) error {
	r := rand.New(rand.NewSource(time.Now().UnixNano()))
	q := icebreakerQuestions[r.Intn(len(icebreakerQuestions))]
	out := "<b>Icebreaker</b>\n\n" + html.EscapeString(q)
	m.Reply(out)
	return nil
}

func WouldYouRatherHandler(m *tg.NewMessage) error {
	r := rand.New(rand.NewSource(time.Now().UnixNano()))
	q := wouldYouRatherQuestions[r.Intn(len(wouldYouRatherQuestions))]
	out := "<b>Would You Rather</b>\n\n" + html.EscapeString(q)
	m.Reply(out)
	return nil
}

func init() { QueueHandlerRegistration(registerRandomTopicHandlers) }
func registerRandomTopicHandlers() {
	c := Client
	c.On("cmd:icebreaker", IcebreakerHandler)
	c.On("cmd:wouldyourather", WouldYouRatherHandler)
}
