package modules

import (
	"html"
	"strings"
	"unicode"

	tg "github.com/amarnathcjd/gogram/telegram"
)

var jargonToSimple = map[string]string{
	"utilize":        "use",
	"utilization":    "use",
	"utilized":       "used",
	"utilizes":       "uses",
	"commence":       "start",
	"commenced":      "started",
	"commencement":   "start",
	"terminate":      "end",
	"terminated":     "ended",
	"termination":    "end",
	"facilitate":     "help",
	"facilitated":    "helped",
	"facilitates":    "helps",
	"facilitation":   "help",
	"endeavor":       "try",
	"endeavour":      "try",
	"endeavored":     "tried",
	"demonstrate":    "show",
	"demonstrated":   "shown",
	"demonstrates":   "shows",
	"demonstration":  "show",
	"approximately":  "about",
	"sufficient":     "enough",
	"sufficiently":   "enough",
	"insufficient":   "not enough",
	"subsequently":   "later",
	"subsequent":     "next",
	"previously":     "before",
	"previous":       "earlier",
	"currently":      "now",
	"current":        "now",
	"presently":      "now",
	"immediately":    "now",
	"immediate":      "quick",
	"frequently":     "often",
	"frequent":       "often",
	"occasionally":   "sometimes",
	"occasional":     "rare",
	"additionally":   "also",
	"additional":     "more",
	"furthermore":    "also",
	"moreover":       "also",
	"however":        "but",
	"nevertheless":   "but",
	"nonetheless":    "still",
	"therefore":      "so",
	"thus":           "so",
	"hence":          "so",
	"accordingly":    "so",
	"consequently":   "so",
	"regarding":      "about",
	"concerning":     "about",
	"pertaining":     "about",
	"abundant":       "plenty",
	"abundance":      "plenty",
	"accomplish":     "do",
	"accomplished":   "done",
	"accomplishment": "feat",
	"acquire":        "get",
	"acquired":       "got",
	"acquisition":    "buy",
	"adequate":       "enough",
	"adequately":     "enough",
	"advantageous":   "useful",
	"advantage":      "edge",
	"aggregate":      "total",
	"aggregation":    "total",
	"allocate":       "give",
	"allocated":      "given",
	"allocation":     "share",
	"alternative":    "other",
	"alternatively":  "or",
	"anticipate":     "expect",
	"anticipated":    "expected",
	"apparent":       "clear",
	"apparently":     "seems",
	"appropriate":    "right",
	"appropriately":  "right",
	"ascertain":      "find out",
	"ascertained":    "found",
	"assistance":     "help",
	"assist":         "help",
	"assisted":       "helped",
	"attempt":        "try",
	"attempted":      "tried",
	"attribute":      "trait",
	"attributes":     "traits",
	"beneficial":     "useful",
	"benefit":        "perk",
	"capability":     "skill",
	"capable":        "able",
	"clarification":  "clarity",
	"clarify":        "explain",
	"commensurate":   "equal",
	"comparable":     "similar",
	"compensation":   "pay",
	"comprehend":     "understand",
	"comprehension":  "grasp",
	"comprehensive":  "full",
	"comprise":       "include",
	"comprised":      "made of",
	"comprises":      "includes",
	"concurrent":     "joint",
	"concurrently":   "together",
	"considerable":   "big",
	"considerably":   "much",
	"construct":      "build",
	"constructed":    "built",
	"construction":   "build",
	"deliberate":     "planned",
	"deliberately":   "on purpose",
	"determine":      "decide",
	"determined":     "decided",
	"discontinue":    "stop",
	"discontinued":   "stopped",
	"disseminate":    "share",
	"dissemination":  "spread",
	"distribute":     "give out",
	"distributed":    "shared",
	"distribution":   "spread",
	"duplicate":      "copy",
	"duplicated":     "copied",
	"duplication":    "copy",
	"effectuate":     "cause",
	"elaborate":      "detail",
	"elaborated":     "explained",
	"eliminate":      "remove",
	"eliminated":     "removed",
	"elimination":    "removal",
	"encounter":      "meet",
	"encountered":    "met",
	"enhance":        "improve",
	"enhanced":       "improved",
	"enhancement":    "boost",
	"enumerate":      "list",
	"enumerated":     "listed",
	"equivalent":     "equal",
	"establish":      "set up",
	"established":    "set up",
	"evaluate":       "judge",
	"evaluated":      "judged",
	"evaluation":     "review",
	"exemplify":      "show",
	"expedite":       "speed up",
	"expedited":      "rushed",
	"expenditure":    "cost",
	"feasible":       "doable",
	"finalize":       "finish",
	"finalized":      "done",
	"fundamental":    "basic",
	"generate":       "make",
	"generated":      "made",
	"generation":     "making",
	"identify":       "spot",
	"identified":     "spotted",
	"identification": "id",
	"illustrate":     "show",
	"illustrated":    "shown",
	"illustration":   "image",
	"implement":      "do",
	"implemented":    "done",
	"implementation": "rollout",
	"indicate":       "show",
	"indicated":      "shown",
	"indication":     "sign",
	"individual":     "person",
	"individuals":    "people",
	"initiate":       "start",
	"initiated":      "started",
	"initiation":     "start",
	"inquire":        "ask",
	"inquiry":        "question",
	"institute":      "start",
	"instituted":     "set up",
	"investigate":    "look into",
	"investigated":   "checked",
	"investigation":  "probe",
	"locate":         "find",
	"located":        "found",
	"location":       "spot",
	"magnitude":      "size",
	"maintain":       "keep",
	"maintained":     "kept",
	"manufacture":    "make",
	"manufactured":   "made",
	"methodology":    "method",
	"minimize":       "lessen",
	"minimized":      "lessened",
	"modification":   "change",
	"modify":         "change",
	"modified":       "changed",
	"necessitate":    "require",
	"necessary":      "needed",
	"notwithstanding": "despite",
	"numerous":       "many",
	"objective":      "goal",
	"obligation":     "duty",
	"observation":    "view",
	"observe":        "see",
	"observed":       "seen",
	"obtain":         "get",
	"obtained":       "got",
	"operate":        "run",
	"operated":       "ran",
	"operation":      "run",
	"optimal":        "best",
	"optimize":       "improve",
	"optimized":      "tuned",
	"option":         "choice",
	"optional":       "extra",
	"originate":      "begin",
	"originated":     "began",
	"participate":    "join",
	"participated":   "joined",
	"participation":  "joining",
	"perceive":       "see",
	"perceived":      "seen",
	"perception":     "view",
	"perform":        "do",
	"performed":      "did",
	"performance":    "result",
	"permit":         "let",
	"permitted":      "allowed",
	"permission":     "ok",
	"persistent":     "lasting",
	"portion":        "part",
	"possess":        "own",
	"possessed":      "owned",
	"possession":     "owning",
	"potential":      "possible",
	"preliminary":    "early",
	"primary":        "main",
	"prioritize":     "rank",
	"procedure":      "step",
	"procure":        "get",
	"procured":       "got",
	"prohibit":       "ban",
	"prohibited":     "banned",
	"prohibition":    "ban",
	"purchase":       "buy",
	"purchased":      "bought",
	"quantify":       "count",
	"reside":         "live",
	"resided":        "lived",
	"residence":      "home",
	"resolve":        "fix",
	"resolved":       "fixed",
	"resolution":     "fix",
	"retain":         "keep",
	"retained":       "kept",
	"select":         "pick",
	"selected":       "picked",
	"selection":      "pick",
	"significant":    "big",
	"significantly":  "much",
	"specify":        "list",
	"specified":      "listed",
	"strategy":       "plan",
	"submit":         "send",
	"submitted":      "sent",
	"sustain":        "keep",
	"sustained":      "kept",
	"transmit":       "send",
	"transmitted":    "sent",
	"transmission":   "send",
	"transparent":    "clear",
	"undertake":      "do",
	"undertook":      "did",
	"validate":       "check",
	"validated":      "checked",
	"validation":     "check",
	"verify":         "check",
	"verified":       "checked",
	"verification":   "check",
	"vicinity":       "area",
	"warrant":        "need",
	"warranted":      "needed",
}

var simpleToFancy = map[string]string{
	"use":        "utilize",
	"used":       "utilized",
	"uses":       "utilizes",
	"start":      "commence",
	"started":    "commenced",
	"starts":     "commences",
	"end":        "terminate",
	"ended":      "terminated",
	"ends":       "terminates",
	"help":       "facilitate",
	"helped":     "facilitated",
	"helps":      "facilitates",
	"try":        "endeavor",
	"tried":      "endeavored",
	"tries":      "endeavors",
	"show":       "demonstrate",
	"showed":     "demonstrated",
	"shown":      "demonstrated",
	"shows":      "demonstrates",
	"about":      "regarding",
	"enough":     "sufficient",
	"later":      "subsequently",
	"next":       "subsequent",
	"before":     "previously",
	"now":        "presently",
	"often":      "frequently",
	"sometimes":  "occasionally",
	"also":       "additionally",
	"more":       "additional",
	"but":        "however",
	"so":         "therefore",
	"plenty":     "abundance",
	"do":         "perform",
	"did":        "performed",
	"done":       "accomplished",
	"get":        "acquire",
	"got":        "acquired",
	"gets":       "acquires",
	"give":       "allocate",
	"gave":       "allocated",
	"gives":      "allocates",
	"other":      "alternative",
	"expect":     "anticipate",
	"expected":   "anticipated",
	"clear":      "transparent",
	"right":      "appropriate",
	"big":        "substantial",
	"small":      "diminutive",
	"fast":       "expeditious",
	"slow":       "lethargic",
	"build":      "construct",
	"built":      "constructed",
	"builds":     "constructs",
	"decide":     "determine",
	"decided":    "determined",
	"stop":       "discontinue",
	"stopped":    "discontinued",
	"share":      "disseminate",
	"shared":     "disseminated",
	"copy":       "duplicate",
	"copied":     "duplicated",
	"copies":     "duplicates",
	"remove":     "eliminate",
	"removed":    "eliminated",
	"meet":       "encounter",
	"met":        "encountered",
	"improve":    "enhance",
	"improved":   "enhanced",
	"list":       "enumerate",
	"listed":     "enumerated",
	"equal":      "equivalent",
	"judge":      "evaluate",
	"judged":     "evaluated",
	"finish":     "finalize",
	"finished":   "finalized",
	"basic":      "fundamental",
	"make":       "generate",
	"made":       "generated",
	"makes":      "generates",
	"spot":       "identify",
	"spotted":    "identified",
	"join":       "participate",
	"joined":     "participated",
	"see":        "observe",
	"saw":        "observed",
	"seen":       "observed",
	"sees":       "observes",
	"run":        "operate",
	"ran":        "operated",
	"runs":       "operates",
	"best":       "optimal",
	"choice":     "option",
	"begin":      "originate",
	"began":      "originated",
	"begins":     "originates",
	"let":        "permit",
	"allowed":    "permitted",
	"own":        "possess",
	"owned":      "possessed",
	"owns":       "possesses",
	"possible":   "potential",
	"main":       "primary",
	"step":       "procedure",
	"ban":        "prohibit",
	"banned":     "prohibited",
	"buy":        "procure",
	"bought":     "procured",
	"buys":       "procures",
	"live":       "reside",
	"lived":      "resided",
	"lives":      "resides",
	"home":       "residence",
	"fix":        "resolve",
	"fixed":      "resolved",
	"fixes":      "resolves",
	"keep":       "retain",
	"kept":       "retained",
	"keeps":      "retains",
	"pick":       "select",
	"picked":     "selected",
	"picks":      "selects",
	"plan":       "strategy",
	"send":       "transmit",
	"sent":       "transmitted",
	"sends":      "transmits",
	"check":      "verify",
	"checked":    "verified",
	"checks":     "verifies",
	"area":       "vicinity",
	"need":       "require",
	"needed":     "required",
	"needs":      "requires",
	"happy":      "elated",
	"sad":        "melancholy",
	"angry":      "irate",
	"tired":      "fatigued",
	"smart":      "perspicacious",
	"smell":      "olfactory sensation",
	"think":      "contemplate",
	"thought":    "contemplated",
	"thinks":     "contemplates",
	"talk":       "converse",
	"talked":     "conversed",
	"talks":      "converses",
	"walk":       "perambulate",
	"walked":     "perambulated",
	"walks":      "perambulates",
	"eat":        "consume",
	"ate":        "consumed",
	"eats":       "consumes",
	"drink":      "imbibe",
	"drank":      "imbibed",
	"drinks":     "imbibes",
	"sleep":      "slumber",
	"slept":      "slumbered",
	"sleeps":     "slumbers",
}

var pirateMap = map[string]string{
	"hello":     "ahoy",
	"hi":        "ahoy",
	"hey":       "arrr",
	"my":        "me",
	"friend":    "matey",
	"friends":   "mateys",
	"yes":       "aye",
	"no":        "nay",
	"is":        "be",
	"are":       "be",
	"am":        "be",
	"the":       "thar",
	"you":       "ye",
	"your":      "yer",
	"yours":     "yers",
	"you're":    "ye be",
	"there":     "thar",
	"over":      "o'er",
	"and":       "an'",
	"of":        "o'",
	"to":        "t'",
	"with":      "wit'",
	"old":       "ol'",
	"good":      "fine",
	"man":       "scallywag",
	"woman":     "lass",
	"men":       "scallywags",
	"women":     "lasses",
	"boy":       "lad",
	"girl":      "lass",
	"boys":      "lads",
	"girls":     "lasses",
	"money":     "doubloons",
	"gold":      "booty",
	"treasure":  "booty",
	"drink":     "grog",
	"drinks":    "grog",
	"beer":      "grog",
	"rum":       "grog",
	"food":      "grub",
	"ship":      "vessel",
	"boat":      "vessel",
	"ocean":     "sea",
	"sea":       "briny deep",
	"flag":      "jolly roger",
	"police":    "navy",
	"officer":   "scallywag",
	"sir":       "cap'n",
	"madam":     "lass",
	"crazy":     "barmy",
	"angry":     "scurvy",
	"stupid":    "scurvy",
	"awesome":   "ship-shape",
	"great":     "grand",
	"amazing":   "splendid",
	"foolish":   "lily-livered",
	"coward":    "lily-livered",
	"strong":    "hearty",
	"brave":     "hearty",
	"weak":      "lily-livered",
	"happy":     "merry",
	"sad":       "downhearted",
	"laugh":     "guffaw",
	"laughed":   "guffawed",
	"yelling":   "bellowin'",
	"shouting":  "bellowin'",
	"shout":     "bellow",
	"shouted":   "bellowed",
	"home":      "port",
	"family":    "crew",
	"team":      "crew",
	"group":     "crew",
	"work":      "swab",
	"working":   "swabbin'",
	"worked":    "swabbed",
	"fight":     "duel",
	"fighting":  "battlin'",
	"fought":    "battled",
	"steal":     "plunder",
	"stole":     "plundered",
	"stealing":  "plunderin'",
	"running":   "runnin'",
	"jumping":   "jumpin'",
	"talking":   "yammerin'",
	"singing":   "singin'",
	"sailing":   "sailin'",
	"fishing":   "fishin'",
	"swimming":  "swimmin'",
	"drinking":  "guzzlin'",
	"eating":    "feastin'",
	"sleeping":  "snorin'",
	"morning":   "mornin'",
	"evening":   "evenin'",
	"nothing":   "nothin'",
	"something": "somethin'",
	"anything":  "anythin'",
	"hello!":    "ahoy!",
	"thanks":    "much obliged",
	"thank":     "thank ye",
	"sorry":     "beggin' yer pardon",
	"please":    "pray",
	"goodbye":   "farewell",
	"bye":       "fare thee well",
	"city":      "port",
	"town":      "port",
	"king":      "cap'n",
	"queen":     "cap'n's wife",
	"boss":      "cap'n",
	"leader":    "cap'n",
}

var shakespeareMap = map[string]string{
	"you":       "thou",
	"your":      "thy",
	"yours":     "thine",
	"yourself":  "thyself",
	"you're":    "thou art",
	"you've":    "thou hast",
	"you'll":    "thou shalt",
	"you'd":     "thou wouldst",
	"are":       "art",
	"is":        "doth be",
	"am":        "be",
	"have":      "hast",
	"has":       "hath",
	"had":       "hadst",
	"do":        "dost",
	"does":      "doth",
	"did":       "didst",
	"will":      "shalt",
	"would":     "wouldst",
	"could":     "couldst",
	"should":    "shouldst",
	"can":       "canst",
	"may":       "mayst",
	"might":     "mightst",
	"hello":     "hail",
	"hi":        "hail",
	"hey":       "hark",
	"goodbye":   "fare thee well",
	"bye":       "farewell",
	"yes":       "aye",
	"no":        "nay",
	"my":        "mine",
	"sir":       "good sir",
	"madam":     "good lady",
	"man":       "gentleman",
	"woman":     "lady",
	"friend":    "good fellow",
	"hello!":    "hail!",
	"please":    "prithee",
	"truly":     "verily",
	"really":    "verily",
	"indeed":    "forsooth",
	"perhaps":   "mayhap",
	"maybe":     "mayhap",
	"before":    "ere",
	"earlier":   "ere",
	"between":   "betwixt",
	"often":     "oft",
	"over":      "o'er",
	"ever":      "e'er",
	"never":     "ne'er",
	"thanks":    "much gratitude",
	"thank":     "thank thee",
	"sorry":     "I beg thy pardon",
	"problem":   "quandary",
	"trouble":   "vexation",
	"crazy":     "mad",
	"angry":     "wroth",
	"happy":     "merry",
	"sad":       "forlorn",
	"good":      "fair",
	"bad":       "foul",
	"great":     "wondrous",
	"awesome":   "wondrous",
	"amazing":   "marvelous",
	"beautiful": "fair",
	"ugly":      "loathsome",
	"smart":     "wise",
	"stupid":    "foolish",
	"speak":     "speaketh",
	"speaks":    "speaketh",
	"think":     "methinks",
	"thinks":    "methinks",
	"go":        "goest",
	"goes":      "goeth",
	"come":      "comest",
	"comes":     "cometh",
	"see":       "seest",
	"sees":      "seeth",
	"know":      "knowest",
	"knows":     "knoweth",
	"say":       "sayest",
	"says":      "sayeth",
	"said":      "didst say",
	"tell":      "tellest",
	"tells":     "telleth",
	"told":      "didst tell",
	"give":      "givest",
	"gives":     "giveth",
	"gave":      "didst give",
	"take":      "takest",
	"takes":     "taketh",
	"took":      "didst take",
	"want":      "desire",
	"wants":     "desireth",
	"wanted":    "didst desire",
	"love":      "adore",
	"loves":     "adoreth",
	"loved":     "didst adore",
	"hate":      "loathe",
	"hates":     "loatheth",
	"need":      "require",
	"needs":     "requireth",
	"work":      "labor",
	"works":     "laboreth",
	"fight":     "duel",
	"fights":    "dueleth",
	"king":      "sovereign",
	"queen":     "majesty",
	"prince":    "noble",
	"princess":  "fair maiden",
	"girl":      "maiden",
	"boy":       "lad",
	"home":      "abode",
	"house":     "manor",
	"food":      "feast",
	"drink":     "draught",
	"money":     "coin",
	"sword":     "blade",
	"horse":     "steed",
	"city":      "kingdom",
	"town":      "village",
}

func emTransformWord(w string, mapping map[string]string) string {
	if w == "" {
		return w
	}
	stripped := w
	leading := ""
	trailing := ""
	for len(stripped) > 0 {
		r := rune(stripped[0])
		if unicode.IsLetter(r) || unicode.IsDigit(r) || r == '\'' {
			break
		}
		leading += string(stripped[0])
		stripped = stripped[1:]
	}
	for len(stripped) > 0 {
		r := rune(stripped[len(stripped)-1])
		if unicode.IsLetter(r) || unicode.IsDigit(r) || r == '\'' {
			break
		}
		trailing = string(stripped[len(stripped)-1]) + trailing
		stripped = stripped[:len(stripped)-1]
	}
	if stripped == "" {
		return w
	}
	lower := strings.ToLower(stripped)
	replacement, ok := mapping[lower]
	if !ok {
		return w
	}
	final := emMatchCase(stripped, replacement)
	return leading + final + trailing
}

func emMatchCase(orig, repl string) string {
	if orig == "" {
		return repl
	}
	allUpper := true
	for _, r := range orig {
		if unicode.IsLetter(r) && !unicode.IsUpper(r) {
			allUpper = false
			break
		}
	}
	if allUpper && len(orig) > 1 {
		return strings.ToUpper(repl)
	}
	firstRune := rune(orig[0])
	if unicode.IsUpper(firstRune) {
		runes := []rune(repl)
		if len(runes) > 0 {
			runes[0] = unicode.ToUpper(runes[0])
			return string(runes)
		}
	}
	return repl
}

func emTransform(text string, mapping map[string]string) string {
	words := strings.Fields(text)
	out := make([]string, len(words))
	for i, w := range words {
		out[i] = emTransformWord(w, mapping)
	}
	return strings.Join(out, " ")
}

func emGetInput(m *tg.NewMessage) string {
	text := strings.TrimSpace(m.Args())
	if text == "" && m.IsReply() {
		r, err := m.GetReplyMessage()
		if err == nil {
			text = strings.TrimSpace(r.Text())
		}
	}
	return text
}

func DejargonHandler(m *tg.NewMessage) error {
	text := emGetInput(m)
	if text == "" {
		m.Reply("<b>Usage:</b> <code>/dejargon &lt;text&gt;</code> or reply to a message.")
		return nil
	}
	out := emTransform(text, jargonToSimple)
	m.Reply("<b>Plain:</b> " + html.EscapeString(out))
	return nil
}

func UpgradeHandler(m *tg.NewMessage) error {
	text := emGetInput(m)
	if text == "" {
		m.Reply("<b>Usage:</b> <code>/upgrade &lt;text&gt;</code> or reply to a message.")
		return nil
	}
	out := emTransform(text, simpleToFancy)
	m.Reply("<b>Fancy:</b> " + html.EscapeString(out))
	return nil
}

func PirateHandler(m *tg.NewMessage) error {
	text := emGetInput(m)
	if text == "" {
		m.Reply("<b>Usage:</b> <code>/pirate &lt;text&gt;</code> or reply to a message.")
		return nil
	}
	out := emTransform(text, pirateMap)
	suffixes := []string{" Arrr!", " Yo ho ho!", " Shiver me timbers!", " Avast!", " Yarrr!"}
	idx := len(text) % len(suffixes)
	out = out + suffixes[idx]
	m.Reply("<b>Pirate:</b> " + html.EscapeString(out))
	return nil
}

func BardSpeakHandler(m *tg.NewMessage) error {
	text := emGetInput(m)
	if text == "" {
		m.Reply("<b>Usage:</b> <code>/bardspeak &lt;text&gt;</code> or reply to a message.")
		return nil
	}
	out := emTransform(text, shakespeareMap)
	suffixes := []string{" Forsooth!", " Verily!", " Anon!", " Hark!", " 'Tis so!"}
	idx := len(text) % len(suffixes)
	out = out + suffixes[idx]
	m.Reply("<b>Bard:</b> " + html.EscapeString(out))
	return nil
}

func registerTranslateEmojiHandlers() {
	c := Client
	c.On("cmd:dejargon", DejargonHandler)
	c.On("cmd:upgrade", UpgradeHandler)
	c.On("cmd:pirate", PirateHandler)
	c.On("cmd:bardspeak", BardSpeakHandler)
}

func init() {
	QueueHandlerRegistration(registerTranslateEmojiHandlers)
}
